In [4]:
# 1.
import numpy as np
arr=np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [6]:
# 2.
arr1=np.array([1,21,3,4,15])
arr2=np.array([62,7,18,9,10])
arr3 = arr1+arr2
arr3.sort()
print(arr3)



[13 21 25 28 63]


In [7]:
# 3.
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(len(arr))

(3, 3)
3


In [11]:
# 4.
arr=np.arange(12)
arr=np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
# 5.
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,1,1],[2,2,2],[3,3,3]])
print(np.vstack(arr1))
print(np.vstack(arr2))
print(np.hstack(arr1))
print(np.hstack(arr2))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[1 2 3 4 5 6 7 8 9]
[1 1 1 2 2 2 3 3 3]


In [14]:
# 6.take a array and convert it into numpy array and then use numpy.unique() function
# this will give u the unique elements of a array or list
import numpy as np
arr = [1,2,2,1,4,3,3,5,3]
A = np.array(arr)
np.unique(A)

array([1, 2, 3, 4, 5])